/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inicializar;

//import java.awt.event.WindowAdapter;
import Data.*;

import Inicializar.FrmAutenticacion;

//import java.awt.event.WindowEvent;
//import javax.swing.JOptionPane;
//import java.awt.event.ActionListener;
//import java.awt.event.ActionEvent;
//import Administrador.CKiosco;
//import java.util.ArrayList;

/**
 *
 * @author lenovo
 */
public class FrmInicio extends javax.swing.JFrame {
   
    private Data data;
    /**
     * Creates new form FrmInicio
     */
    public FrmInicio(Data data) {
        initComponents();
        this.data=data;
        setExtendedState(FrmInicio.MAXIMIZED_BOTH);
        this.setTitle("USAC-Delivery");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JPanel();
        lbBienvenida = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbBienvenida.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        lbBienvenida.setForeground(new java.awt.Color(102, 153, 255));
        lbBienvenida.setText("Bienvenido a USAC-Delivery");

        btnInicioSesion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        btnRegistrarse.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap(621, Short.MAX_VALUE)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                        .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                        .addComponent(lbBienvenida)
                        .addGap(363, 363, 363))))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225)
                .addComponent(lbBienvenida)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
      
       if(evt.getSource()==btnRegistrarse){
            FrmRegistroUsuario frmRegistroUsuario = new FrmRegistroUsuario(data);
            frmRegistroUsuario.setDefaultCloseOperation(FrmRegistroUsuario.DISPOSE_ON_CLOSE);
            frmRegistroUsuario.setLocationRelativeTo(null);
            frmRegistroUsuario.setVisible(true);
       }
        
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btnInicioSesion){
           FrmAutenticacion frmAutenticacion = new FrmAutenticacion(data);     
            frmAutenticacion.setDefaultCloseOperation(FrmAutenticacion.DISPOSE_ON_CLOSE);
            frmAutenticacion.setLocationRelativeTo(null);
            frmAutenticacion.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

        public void CloseAutenticacion(){
            super.dispose();
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel lbBienvenida;
    // End of variables declaration//GEN-END:variables
}
