/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

import Data.*;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
/**
 *
 * @author lenovo
 */
public class FrmKiosco extends javax.swing.JFrame {
    
        String codigo="";
        String nombre="";
        String region="";
        public ArrayList<CKiosco> listaKioscos;
        
        Data data;
        
    public FrmKiosco(Data data) {
        initComponents();   
        this.data=data;
        listaKioscos = data.getListaKioscos();
        this.setTitle("Manejo Kioscos");

        
        jTableKioscos.addMouseListener(new MouseAdapter(){
        
        public void mouseClicked(MouseEvent e){
        int i = jTableKioscos.getSelectedRow();
        txtCodigoKiosco.setEditable(false);
        codigo = (jTableKioscos.getValueAt(i, 0).toString());
        nombre = (jTableKioscos.getValueAt(i, 1).toString());
        region = (jTableKioscos.getValueAt(i, 2).toString());
        }});        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreKiosco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboBoxRegionKiosco = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoKiosco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKioscos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setText("Manejo de Kioscos");

        jLabel3.setText("Nombre Kiosco");

        comboBoxRegionKiosco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione Region-", "(M) Metropolitana", "(NT) Norte", "(NO) Nororiente", "(SO) Suroriente", "(SOC) Suroccidente", "(NOC) Noroccidente" }));
        comboBoxRegionKiosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRegionKioscoActionPerformed(evt);
            }
        });

        jLabel4.setText("Region de Kiosco");

        jLabel5.setText("Codigo de Kiosco");

        jTableKioscos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Region"
            }
        ));
        jTableKioscos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableKioscos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableKioscos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableKioscos.setShowGrid(true);
        jTableKioscos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKioscosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKioscos);

        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCodigoKiosco)
                                    .addComponent(txtNombreKiosco)
                                    .addComponent(comboBoxRegionKiosco, 0, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnAgregar)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar)
                                .addGap(25, 25, 25)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(txtCodigoKiosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(txtNombreKiosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRegionKiosco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombreKiosco = txtNombreKiosco.getText().trim();
        String codigoKiosco = txtCodigoKiosco.getText().trim();
        String regionKiosco=comboBoxRegionKiosco.getSelectedItem().toString(); 
        
        if( nombreKiosco.isBlank() || 
            codigoKiosco.isBlank() || 
            regionKiosco.contentEquals("-Seleccione Region-") ){
            JOptionPane.showMessageDialog( this,  "Todos los campos son obligatorios");
            limpiarCampos();
            return;
        }
        
       if( data.existeKiosco(codigoKiosco, nombreKiosco)){
           JOptionPane.showMessageDialog( this,  "El Kiosco ya existe!");
            LimpiarFormulario();
       }
       else{
           CKiosco kiosco = new CKiosco( codigoKiosco, nombreKiosco,regionKiosco);
     
            listaKioscos.add(kiosco);
            
            mostrarDatos();
            LimpiarFormulario();
       }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void comboBoxRegionKioscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRegionKioscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRegionKioscoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombreKiosco = txtNombreKiosco.getText().trim();
        String codigoKiosco = txtCodigoKiosco.getText().trim();
        String regionKiosco=comboBoxRegionKiosco.getSelectedItem().toString();
        
        if( nombreKiosco.isBlank() || 
            codigoKiosco.isBlank() || 
            regionKiosco.contentEquals("-Seleccione Region-") ){
            JOptionPane.showMessageDialog( this,  "No hay datos para eliminar");
            txtCodigoKiosco.setText("");
            txtNombreKiosco.setText("");
            comboBoxRegionKiosco.requestFocus();
            return;
        }
        
        data.eliminarKiosco(codigoKiosco);
        txtCodigoKiosco.setEditable(true);

        limpiarCampos();
        mostrarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        String codigoKiosco = txtCodigoKiosco.getText().trim();
        String nombreKiosco = txtNombreKiosco.getText().trim();
        String nombreRegion = comboBoxRegionKiosco.getSelectedItem().toString();
        
        data.actualizarKiosco(codigoKiosco, nombreKiosco, nombreRegion);
        txtCodigoKiosco.setEditable(true);
        
        limpiarCampos();
        mostrarDatos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void limpiarCampos(){
        txtCodigoKiosco.setText("");
        txtNombreKiosco.setText("");
        comboBoxRegionKiosco.setSelectedItem("-Seleccione Region-");
    }
    
    private void jTableKioscosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKioscosMouseClicked
        JTable table = (JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = table.rowAtPoint(point);
        
        txtCodigoKiosco.setText(listaKioscos.get(row).getCodigoKiosco());
        txtNombreKiosco.setText ( listaKioscos.get(row).getNombreKiosco()); 
        comboBoxRegionKiosco.setSelectedItem(listaKioscos.get(row).getRegionKiosco());
    }//GEN-LAST:event_jTableKioscosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
            FrmAdmin frmAdmin = new FrmAdmin(data);
            frmAdmin.setDefaultCloseOperation(FrmAdmin.DISPOSE_ON_CLOSE);
            frmAdmin.setLocationRelativeTo(null);
            frmAdmin.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed
    
    public void mostrarDatos(){
        String GuardarDatos[][] = new String[listaKioscos.size()][20];
    
        for (int i = 0; i < listaKioscos.size(); i++) {
            
            GuardarDatos[i][0]=listaKioscos.get(i).getCodigoKiosco();
            GuardarDatos[i][1]=listaKioscos.get(i).getNombreKiosco();
            GuardarDatos[i][2]=listaKioscos.get(i).getRegionKiosco();
        }
        jTableKioscos.setModel(new javax.swing.table.DefaultTableModel(GuardarDatos, new String [] {"Codigo","Nombre","Region"}) );
    } 
    
    public void LimpiarFormulario(){
        txtCodigoKiosco.setText("");
        txtNombreKiosco.setText("");
        comboBoxRegionKiosco.setSelectedIndex(0);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboBoxRegionKiosco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKioscos;
    private javax.swing.JTextField txtCodigoKiosco;
    private javax.swing.JTextField txtNombreKiosco;
    // End of variables declaration//GEN-END:variables
}
