/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kiosco;
import Data.*;
import Administrador.FrmAdmin;
import Inicializar.FrmInicio;
import Usuario.FrmCotizacion;
import Usuario.FrmEtiquetaEnvio;
import Usuario.FrmRegistroFactura;
import Usuario.FrmRegistroTarjetas;
import Usuario.FrmUser;

public class FrmKioscoMenu extends javax.swing.JFrame {
   private Data data;
    /**
     * Creates new form FrmKioscoMenu
     */
    public FrmKioscoMenu(Data data) {
        initComponents();
        this.data=data;
        this.setTitle("Usuario/Kiosco");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistroTarjeta = new javax.swing.JButton();
        btnDatosFactura = new javax.swing.JButton();
        btnDescargarGuia = new javax.swing.JButton();
        btnCotizar = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a Kiosco");

        btnRegistroTarjeta.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnRegistroTarjeta.setText("Registro de tarjetas credito/debito");
        btnRegistroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroTarjetaActionPerformed(evt);
            }
        });

        btnDatosFactura.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnDatosFactura.setText("Registro datos de facturacion");
        btnDatosFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosFacturaActionPerformed(evt);
            }
        });

        btnDescargarGuia.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnDescargarGuia.setText("Descargar Factura y guia");
        btnDescargarGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarGuiaActionPerformed(evt);
            }
        });

        btnCotizar.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnCotizar.setText("Cotizacion de Paquetes");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        btnCerrarSesion.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCotizar))
                    .addComponent(btnRegistroTarjeta)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDescargarGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnDatosFactura))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroTarjeta)
                .addGap(18, 18, 18)
                .addComponent(btnDatosFactura)
                .addGap(18, 18, 18)
                .addComponent(btnDescargarGuia)
                .addGap(18, 18, 18)
                .addComponent(btnCotizar)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroTarjetaActionPerformed
        if(evt.getSource()== btnRegistroTarjeta){

            FrmRegistroTarjetas frmRegistroTarjetas = new FrmRegistroTarjetas(data);
            frmRegistroTarjetas.setDefaultCloseOperation(FrmUser.DISPOSE_ON_CLOSE);
            frmRegistroTarjetas.setLocationRelativeTo(null);
            frmRegistroTarjetas.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnRegistroTarjetaActionPerformed

    private void btnDatosFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosFacturaActionPerformed
        if(evt.getSource()== btnDatosFactura){
            FrmRegistroFactura frmRegistroFactura = new FrmRegistroFactura(data);
            frmRegistroFactura.setDefaultCloseOperation(FrmUser.DISPOSE_ON_CLOSE);
            frmRegistroFactura.setLocationRelativeTo(null);
            frmRegistroFactura.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnDatosFacturaActionPerformed

    private void btnDescargarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarGuiaActionPerformed
        if(evt.getSource()== btnDescargarGuia){
            FrmEtiquetaEnvio frmEtiquetaEnvio = new FrmEtiquetaEnvio(data);
            frmEtiquetaEnvio.setDefaultCloseOperation(FrmUser.DISPOSE_ON_CLOSE);
            frmEtiquetaEnvio.setLocationRelativeTo(null);
            frmEtiquetaEnvio.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnDescargarGuiaActionPerformed

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        if(evt.getSource()== btnCotizar){
            FrmCotizacion frmCotizacion = new FrmCotizacion(data);
            frmCotizacion.setDefaultCloseOperation(FrmUser.DISPOSE_ON_CLOSE);
            frmCotizacion.setLocationRelativeTo(null);
            frmCotizacion.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnCotizarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        //--setear usuario actual
        CUsuario usuarioActual = data.getUsuarioActual();
        usuarioActual = null;

        FrmInicio frmInicio = new FrmInicio(data);
        frmInicio.setLocationRelativeTo(null);
        frmInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCotizar;
    private javax.swing.JButton btnDatosFactura;
    private javax.swing.JButton btnDescargarGuia;
    private javax.swing.JButton btnRegistroTarjeta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
